[package]
name = "obrc-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20.0"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
env_logger = "0.11"
flume = "0.11"